Assignment_1/Assignment_1/Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Assignment_1.ActionFilters;

namespace Assignment_1.Controllers
{
    public class ChatController : Controller
    {
        Models.ManagerEntities5 context = new Models.ManagerEntities5();

        // GET: Home
        [LoginFilter]
        public ActionResult Index()
        {
            return View();
        }

        // GET: Chat
        public ActionResult Chat()
        {
            String name = "name here";
            ViewBag.recipient_name = name;
            return View();
        }
    }
}

Assignment_1/Assignment_1/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace Assignment_1.Controllers
{
    public class LoginController : Controller
    {
        Models.ManagerEntities5 context = new Models.ManagerEntities5();
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        // POST: Login/Create
        [HttpPost]
        public ActionResult Index(FormCollection collection)
        {
            try
            {
                string username = collection["user_name"];

                var theUser = context.Users.SingleOrDefault(u => u.user_name == username);

                if (theUser != null)
                {
                    Session["user_id"] = theUser.user_id;
                    Session["username"] = theUser.user_name;

                    var theProfile = context.ProfileInformations.FirstOrDefault(p => p.user_name == username);
                    if (theProfile == null)
                    {
                        return RedirectToAction("Create", "Profile", new { id = theUser.user_id, user_name = theUser.user_name });
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home", new { id = theUser.user_id });
                    }
                }
                else
                {
                    return Content("The username does not exist. Click \"Register\" to create a user.");
                }
            }
            catch
            {
                return Content("Login error!");
            }
        }

        // GET: Login/Register
        public ActionResult Register()
        {
            return View();
        }

        // POST: Login/Register
        [HttpPost]
        public ActionResult Register(FormCollection collection)
        {
            //try
            {
                // TODO: Add insert logic here
                Models.User newUser = new Models.User()
                {
                    user_name = collection["user_name"],
                    password = Crypto.HashPassword(collection["password"])
                };
                context.Users.Add(newUser);
                context.SaveChanges();

                return RedirectToAction("Create", "Profile", new { id = newUser.user_id, user_name = newUser.user_name });
            }
            //catch
            {
                //return View();
            }
        }

        // GET: Login/
        public ActionResult Logout()
        {
            Session.Abandon();

            return RedirectToAction("Index");
        }
    }
}



//use in query to reset identity count:
//DBCC CHECKIDENT ([User], RESEED, 0)

Assignment_1/Assignment_1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />

    <div style="background-color:#395999;">
        <div class="container" style="background-color:#395999; padding-top: 10px; padding-bottom: 10px; padding-left: 0px;">
            <div style="float:left">
                <img src="~/Pictures/facebook_logo.png" />
            </div>
            <div style="float:right">
                @if (Session["user_id"] != null)
                {
                    <!--Html.ActionLink("Feed", "Index", "Feed", new { id = ViewBag.profile_id }, new { style = "color:#eeeeee;", class = "navbar-brand" })-->
                    <!--Html.ActionLink("My Profile", "Index", "Home", new { area = "" }, new { style = "color:#eeeeee;", class = "navbar-brand" })-->
                    @Html.ActionLink("Messages", "Chat", "Chat", new { area = "" }, new { @style = "color:#eeeeee;", @class = "navbar-brand" })
                    @Html.ActionLink("Log Out", "Logout", "Login", new { area = "" }, new { @style = "color:#eeeeee;", @class = "navbar-brand" })
                }
            </div>
        </div>
    </div>

    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body style="background-color:#edf0f5">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Our Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        <div>
            @RenderBody()
        </div>
        <hr />
        <div>
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
                <p>This is a school project. Please do not sue us!</p>
                <p>Made by: Loriana G. Maxim & Timothy Eaton</p>
            </footer>
        </div>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>
@RenderSection("scripts", required: false)